application: carstensmithsvenner
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.api

- url: /(.*\.(jpeg|gif|png|jpg|ico|js|css|pdf))
  static_files: \1
  upload: (.*\.(jpeg|gif|png|jpg|ico|js|css|pdf))

- url: .*
  script: main.application

